using System;
using UnityEngine;

// The game's audio, as data (M18e): sound effects (one or more clips each, with a loudness), per-age
// ambience layers, per-age music playlists and the shared night / fire loops. Generated by
// Tools/gen_audio.py; replace any clip in the Inspector with hand-made audio. Music playlists ship
// empty: add tracks and they play with gaps and crossfades. Any missing clip is simply silent.
[CreateAssetMenu(fileName = "AudioCatalog", menuName = "CityBuilder/Audio Catalog")]
public sealed class AudioCatalog : ScriptableObject
{
    [Serializable]
    public sealed class SfxEntry
    {
        public SfxId Id;
        [Range(0f, 1f)] public float Volume = 0.7f;
        public AudioClip[] Clips = Array.Empty<AudioClip>();
    }

    [Serializable]
    public sealed class AmbienceSet
    {
        [Tooltip("Nature / wind: loudest in small towns and zoomed in.")]
        public AudioClip Base;
        [Tooltip("Crowds, carts, traffic: follows the population in view.")]
        public AudioClip City;
        [Tooltip("Workshops, mills, factories: follows the share of industry in view.")]
        public AudioClip Industry;
    }

    [Serializable]
    public sealed class MusicSet
    {
        public AudioClip[] Tracks = Array.Empty<AudioClip>();
    }

    [SerializeField] private SfxEntry[] m_Sfx = Array.Empty<SfxEntry>();
    [Tooltip("Per age index: Medieval, Renaissance, Industrial, Modern.")]
    [SerializeField] private AmbienceSet[] m_Ambience = Array.Empty<AmbienceSet>();
    [Tooltip("Per age index. Empty = no music.")]
    [SerializeField] private MusicSet[] m_Music = Array.Empty<MusicSet>();
    [SerializeField] private AudioClip m_Night;
    [SerializeField] private AudioClip m_Fire;

    public AudioClip Night => m_Night;
    public AudioClip Fire => m_Fire;

    public SfxEntry GetSfx(SfxId id)
    {
        foreach (SfxEntry entry in m_Sfx)
        {
            if (entry != null && entry.Id == id) return entry.Clips != null && entry.Clips.Length > 0 ? entry : null;
        }
        return null;
    }

    public AmbienceSet GetAmbience(int age) => Pick(m_Ambience, age);

    public MusicSet GetMusic(int age) => Pick(m_Music, age);

    private static T Pick<T>(T[] list, int age) where T : class
    {
        if (list == null || list.Length == 0) return null;
        return list[Mathf.Clamp(age, 0, list.Length - 1)];
    }
}
