using UnityEngine;

// Road and ground art for the tilemaps (M18c), generated by Tools/gen_tiles.py and replaceable with
// hand-made sprites: 64 x 64 px at 64 pixels per unit, one cell each. Roads: a sprite per tier (1..5) and
// connection mask (North 1, East 2, South 4, West 8, logical directions; the sprite's texture row 0 is
// logical north, see RoadTilemapView). Ground: GroundVariants sprites per age index, picked per cell by a
// hash. Any missing entry falls back to the runtime-drawn road / the scene's ground tile, so the game plays
// without the set. Ground edges must be plain (no detail within a few pixels of the border) so any two
// variants tile seamlessly.
[CreateAssetMenu(fileName = "TileArtSet", menuName = "CityBuilder/Tile Art Set")]
public sealed class TileArtSet : ScriptableObject
{
    public const int GroundVariants = 4;
    private const int k_Masks = 16;

    [Tooltip("(tier - 1) * 16 + connection mask")]
    [SerializeField] private Sprite[] m_Roads = System.Array.Empty<Sprite>();
    [Tooltip("age index * 4 + variant")]
    [SerializeField] private Sprite[] m_Ground = System.Array.Empty<Sprite>();

    public Sprite Road(int tier, int mask)
    {
        int i = (tier - 1) * k_Masks + mask;
        return tier >= 1 && mask >= 0 && mask < k_Masks && m_Roads != null && i < m_Roads.Length ? m_Roads[i] : null;
    }

    public Sprite Ground(int age, int variant)
    {
        int i = age * GroundVariants + variant;
        return age >= 0 && variant >= 0 && variant < GroundVariants && m_Ground != null && i < m_Ground.Length ? m_Ground[i] : null;
    }
}
