using System;
using UnityEngine;

// The cosmetic vehicles per age (M18f), generated by the building kit generator: one list of prefabs per age
// index (Medieval .. Modern). Each prefab is one mesh on the shared Kit material, front toward +Z, standing on
// the ground, with no collider. A missing age falls back to the nearest earlier one that has vehicles.
[CreateAssetMenu(fileName = "VehicleSet", menuName = "CityBuilder/Vehicle Set")]
public sealed class VehicleSet : ScriptableObject
{
    [Serializable]
    public struct AgeVehicles
    {
        public GameObject[] Prefabs;
    }

    [SerializeField] private AgeVehicles[] m_Ages = Array.Empty<AgeVehicles>();

    public GameObject[] ForAge(int age)
    {
        if (m_Ages == null || m_Ages.Length == 0) return Array.Empty<GameObject>();
        for (int a = Mathf.Clamp(age, 0, m_Ages.Length - 1); a >= 0; a--)
        {
            if (m_Ages[a].Prefabs != null && m_Ages[a].Prefabs.Length > 0) return m_Ages[a].Prefabs;
        }
        return Array.Empty<GameObject>();
    }
}
